# Input = file content (fc) as a big string
# Output = finished, polished .rst file to be directly included
def convert_explanatory(fc):
  # For now, just return dummy input independently of file contents, TODO:: implement actual logic
  return """.. _wrapper-set:

Wrapper set function
====================

.. function:: set(input)

  Tell classy to use certain input parameters, described in the python dictionary ``input``.
  Can also be passed as explicit keywords

  :param input: Input parameters
  :type input: dict

Detailed list of input parameters
---------------------------------

This section will be auto-generated by the custom python script! If you see this, the python script probably failed, please report to the developers!
"""
